baseurl = "/"
languageCode = "en-us"
title = "Personal notes website"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[params]
    description = "A collection of short notes."
    footer = "[Home](/)"
